"""Adversarial stress tests: turbo features=\"all\" vs openpyxl.

Fixtures are generated by tests_turbo/gen_stress.py into testdata/stress_*.xlsx.
Auto-generates missing fixtures on collection (fixed seed).

Coordinate mapping (same as test_oracle):
  turbo data (row r, col c) 0-based → openpyxl (row r+2, col c+1)
  header = spreadsheet row 1

Documented deviations asserted (not fixed):
  - Booleans: turbo yields native Arrow bool (BooleanArray), not Float64 0/1
  - Mixed-type columns: once a column is typed Num, later strings become null
    (LIMITATION — columnar type is sticky; architectural)
  - Formula cells without a cached <v> are null on the value path (both-not-XOR
    still requires a cache for the value column)
"""

from __future__ import annotations

import sys
from datetime import date, datetime
from pathlib import Path

import openpyxl
import pytest
from openpyxl.utils import get_column_letter
from openpyxl.utils.datetime import to_excel

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))

from kyrax import read_excel_turbo  # noqa: E402

TESTDATA = ROOT / "testdata"

STRESS_FILES = [
    "stress_sparse.xlsx",
    "stress_multisheet.xlsx",
    "stress_onecell_everything.xlsx",
    "stress_types.xlsx",
    "stress_noshared.xlsx",
    "stress_nostyles.xlsx",
]


def _is_debug_extension() -> bool:
    """True when the loaded ``_kyrax`` extension is an unoptimized debug build.

    Debug cargo builds embed no optimizations and cannot be judged by an absolute
    release performance threshold. A build is identified as debug only on exact
    byte-identity with ``target/debug/kyrax.dll``; anything else is treated as a
    release build and must still satisfy the timing gate.
    """
    try:
        import kyrax._kyrax as ext

        ext_path = Path(ext.__file__).resolve()
        ext_size = ext_path.stat().st_size
        debug_dll = (ROOT / "target" / "debug" / "kyrax.dll").resolve()
        if not debug_dll.exists():
            return False
        return (
            ext_size == debug_dll.stat().st_size
            and ext_path.read_bytes() == debug_dll.read_bytes()
        )
    except (ImportError, OSError):
        return False


def _ensure_fixtures() -> None:
    missing = [n for n in STRESS_FILES if not (TESTDATA / n).exists()]
    if not missing:
        return
    # Generate all stress fixtures (idempotent, fixed seed).
    import tests_turbo.gen_stress as gen

    gen.main()


def setup_module(module):  # noqa: ARG001
    _ensure_fixtures()


def turbo_to_oxl(row: int, col: int) -> tuple[int, int]:
    return row + 2, col + 1


def cell_value(rb, row: int, col: int):
    return rb.column(col)[row].as_py()


def values_equal(tv, ov, *, rel: float = 1e-6) -> bool:
    if tv is None and ov is None:
        return True
    if isinstance(ov, bool):
        # Native Arrow booleans: turbo yields Python True/False, not Float64 0/1.
        return (tv is True) if ov else (tv is False)
    if isinstance(ov, datetime):
        try:
            # Turbo date32/timestamp columns surface native date/datetime objects;
            # numeric columns surface Excel serials. Normalize either to a serial.
            serial = to_excel(tv) if isinstance(tv, (date, datetime)) else float(tv)
            return abs(serial - float(to_excel(ov))) <= rel * max(1.0, abs(float(to_excel(ov))))
        except (TypeError, ValueError):
            return False
    if isinstance(ov, date) and not isinstance(ov, datetime):
        try:
            serial = to_excel(tv) if isinstance(tv, (date, datetime)) else float(tv)
            return abs(serial - float(to_excel(ov))) <= rel * max(1.0, abs(float(to_excel(ov))))
        except (TypeError, ValueError):
            return False
    # openpyxl may surface Excel serial 0 as datetime.time(0,0)
    from datetime import time as dtime

    if isinstance(ov, dtime):
        try:
            tv_serial = to_excel(tv) if isinstance(tv, (date, datetime)) else float(tv)
            return abs(tv_serial - float(to_excel(ov))) <= 1e-9
        except (TypeError, ValueError):
            # serial 0 ↔ midnight
            try:
                tv_serial = to_excel(tv) if isinstance(tv, (date, datetime)) else float(tv)
                return abs(tv_serial - 0.0) <= 1e-15 and ov.hour == 0 and ov.minute == 0
            except (TypeError, ValueError):
                return False
    if isinstance(tv, float) and isinstance(ov, (int, float)) and not isinstance(ov, bool):
        if tv != tv and (isinstance(ov, float) and ov != ov):
            return True
        return abs(float(tv) - float(ov)) <= rel * max(1.0, abs(float(ov)))
    if isinstance(tv, (int, float)) and isinstance(ov, (int, float)) and not isinstance(ov, bool):
        return abs(float(tv) - float(ov)) <= rel * max(1.0, abs(float(ov)))
    if ov is not None and (
        type(ov).__name__ in ("ErrorCode", "CellError")
        or (isinstance(ov, str) and ov.startswith("#"))
    ):
        return str(tv) == str(ov)
    return tv == ov


# ---------------------------------------------------------------------------
# 1. Sparse rows / columns / gaps
# ---------------------------------------------------------------------------


def test_stress_sparse_coordinates():
    """Every non-empty cell lands at the SAME (row, col) as openpyxl."""
    path = TESTDATA / "stress_sparse.xlsx"
    sheet = read_excel_turbo(str(path)).load_sheet(0, features="all")
    rb = sheet.to_arrow()
    style_idx = sheet.style_indices()
    style_table = sheet.style_table()
    assert style_idx is not None and style_table is not None

    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb.active

    mismatches = []
    null_mismatches = []
    style_mismatches = []
    checked_nonzero = 0

    # Determine shared max extent
    max_r = max(sheet.nrows + 1, ws.max_row or 1)  # sheet row
    max_c = max(sheet.ncols, ws.max_column or 1)

    # Turbo must cover at least openpyxl's used range for data rows
    # (header excluded): data rows = sheet rows 2..max_row
    assert sheet.ncols >= 1

    for orow in range(2, (ws.max_row or 1) + 1):
        for ocol in range(1, (ws.max_column or 1) + 1):
            ov = ws.cell(orow, ocol).value
            tr = orow - 2
            tc = ocol - 1
            if tr < 0:
                continue
            if tr >= sheet.nrows or tc >= sheet.ncols:
                if ov is not None:
                    mismatches.append(
                        ("oob", orow, ocol, ov, f"turbo nrows={sheet.nrows} ncols={sheet.ncols}")
                    )
                continue
            tv = cell_value(rb, tr, tc)
            if ov is None:
                if tv is not None:
                    null_mismatches.append((orow, ocol, tv))
                    if len(null_mismatches) >= 12:
                        break
                continue
            if not values_equal(tv, ov):
                mismatches.append((orow, ocol, tv, ov))
                if len(mismatches) >= 12:
                    break
                continue
            checked_nonzero += 1
            # number_format via style index
            xf = style_idx[tc][tr]
            rust_fmt = style_table[xf]["number_format"]
            oxl_fmt = ws.cell(orow, ocol).number_format or "General"
            if rust_fmt != oxl_fmt and not (
                rust_fmt in ("General", "general") and oxl_fmt in ("General", "general")
            ):
                if oxl_fmt not in ("General", "general"):
                    style_mismatches.append((orow, ocol, rust_fmt, oxl_fmt))
        if len(mismatches) >= 12 or len(null_mismatches) >= 12:
            break

    wb.close()

    # Hard-coded sparse patterns from gen_stress
    # A10=100, C10=300 (no B10); D15=400; A20=1, C20 formula
    hard = []
    wb2 = openpyxl.load_workbook(path, data_only=False)
    ws2 = wb2.active
    for addr, exp_col_letter in [("A10", "A"), ("C10", "C"), ("D15", "D"), ("A20", "A")]:
        cell = ws2[addr]
        orow, ocol = cell.row, cell.column
        tr, tc = orow - 2, ocol - 1
        tv = cell_value(rb, tr, tc)
        if cell.value is not None and not isinstance(cell.value, str):
            if not values_equal(tv, cell.value):
                hard.append((addr, tv, cell.value, tr, tc))
        # ensure coordinate letter matches
        if get_column_letter(tc + 1) != exp_col_letter:
            hard.append((addr, "col_letter", get_column_letter(tc + 1), exp_col_letter))
    # B10 must be null while A10 and C10 set
    tr, tc = 10 - 2, 2 - 1  # B10
    if tr < sheet.nrows and cell_value(rb, tr, tc) is not None:
        # only if openpyxl also has None
        if ws2["B10"].value is None:
            hard.append(("B10", "expected null", cell_value(rb, tr, tc)))
    # formula at C20
    formulas = sheet.formulas()
    assert formulas is not None
    fpd = formulas.to_pydict()
    found_c20 = False
    for i in range(formulas.num_rows):
        if fpd["row"][i] == 20 - 2 and fpd["col"][i] == 3 - 1:
            found_c20 = True
            assert "A20" in (fpd["text"][i] or "")
    if not found_c20:
        hard.append(("C20 formula missing at (18, 2)", fpd["row"][:5], fpd["col"][:5]))
    wb2.close()

    assert checked_nonzero > 100, f"too few non-empty cells checked: {checked_nonzero}"
    assert not hard, f"hard sparse patterns failed: {hard}"
    assert not mismatches, f"value mismatches e.g. {mismatches[:8]}"
    assert not null_mismatches, f"null mismatches e.g. {null_mismatches[:8]}"
    assert not style_mismatches, f"number_format mismatches e.g. {style_mismatches[:8]}"


# ---------------------------------------------------------------------------
# 2. Multi-sheet
# ---------------------------------------------------------------------------


def test_stress_multisheet_by_name_and_index():
    path = TESTDATA / "stress_multisheet.xlsx"
    reader = read_excel_turbo(str(path))
    names = reader.sheet_names
    assert names == ["Values", "MergedLinks", "Comments", "Empty"]

    wb = openpyxl.load_workbook(path, data_only=True)
    wb_f = openpyxl.load_workbook(path, data_only=False)

    for idx, name in enumerate(names):
        by_i = reader.load_sheet(idx, features="all")
        by_n = reader.load_sheet(name, features="all")
        assert by_i.name == by_n.name == name
        assert by_i.nrows == by_n.nrows
        assert by_i.ncols == by_n.ncols

        ws = wb[name]
        ws_f = wb_f[name]

        if name == "Empty":
            # empty-but-valid: every accessor under features="all" must not panic
            rb = by_i.to_arrow()
            assert rb.num_rows == by_i.nrows == 0
            assert by_i.merges() is not None
            assert by_i.hyperlinks() is not None
            assert by_i.comments() is not None
            assert by_i.tables() is not None
            # style_table is workbook-level; may be present via features=all
            st = by_i.style_table()
            assert st is not None or st is None  # must not raise
            # style_indices may be None when ncols==0 (no columns to index)
            _ = by_i.style_indices()
            f = by_i.formulas()
            if f is not None:
                assert f.num_rows == 0
            c = by_i.comments()
            assert c is not None and c.num_rows == 0
            assert isinstance(by_i.merges(), list)
            assert isinstance(by_i.hyperlinks(), list)
            assert isinstance(by_i.tables(), list)
            continue

        rb = by_i.to_arrow()
        # sample values
        for orow in range(2, min((ws.max_row or 1), 20) + 1):
            for ocol in range(1, min((ws.max_column or 1), 5) + 1):
                ov = ws.cell(orow, ocol).value
                tr, tc = orow - 2, ocol - 1
                if tr >= by_i.nrows or tc >= by_i.ncols:
                    if ov is not None:
                        pytest.fail(f"{name}: turbo oob for {orow},{ocol} val={ov}")
                    continue
                tv = cell_value(rb, tr, tc)
                assert values_equal(tv, ov), f"{name} ({orow},{ocol}): turbo={tv!r} oxl={ov!r}"

        if name == "MergedLinks":
            merges = by_i.merges()
            assert merges is not None
            oxl_m = set(str(r) for r in ws_f.merged_cells.ranges)
            assert set(merges) == oxl_m, f"merges {set(merges)!r} vs {oxl_m!r}"
            hlinks = by_i.hyperlinks()
            assert hlinks is not None and len(hlinks) >= 1
            # at least one external link to example.com
            targets = [h.get("target") or "" for h in hlinks]
            assert any("example.com" in t for t in targets), targets

        if name == "Comments":
            comments = by_i.comments()
            assert comments is not None and comments.num_rows >= 3
            cpd = comments.to_pydict()
            refs = set(cpd["ref"])
            assert "A2" in refs and "B5" in refs
            tables = by_i.tables()
            assert tables is not None
            assert any(t["name"] == "TblComments" for t in tables)

        if name == "Values":
            tables = by_i.tables()
            assert tables is not None
            assert any(t["name"] == "TblValues" for t in tables)
            assert by_i.nrows == 100
            assert by_i.ncols == 5

    # Defined names: sheet-scoped resolve to correct sheet indices
    # Re-load any sheet with defined_names flag
    _ = reader.load_sheet(0, features="all")
    dns = reader.defined_names()
    assert dns is not None
    scoped = [d for d in dns if d.get("scope") is not None]
    # Expect sheet-scoped names on sheets 2 (idx 1) and 4 (idx 3)
    scopes = {int(d["scope"]) for d in scoped}
    # At least one name scoped to sheet index 1 or 3
    assert scopes & {1, 3} or any(
        "Sheet2" in (d.get("name") or "") or "Empty" in (d.get("name") or "") or "Local" in (d.get("name") or "")
        for d in dns
    ), f"expected sheet-scoped names, got {dns}"

    # If scope present, verify index matches openpyxl localSheetId
    for d in scoped:
        sc = int(d["scope"])
        assert 0 <= sc < len(names), f"scope {sc} out of range for {d}"

    wb.close()
    wb_f.close()


# ---------------------------------------------------------------------------
# 3. One cell with everything
# ---------------------------------------------------------------------------


def test_stress_onecell_everything():
    path = TESTDATA / "stress_onecell_everything.xlsx"
    sheet = read_excel_turbo(str(path)).load_sheet(0, features="all")
    rb = sheet.to_arrow()
    style_idx = sheet.style_indices()
    style_table = sheet.style_table()
    assert style_idx is not None and style_table is not None

    merges = sheet.merges()
    assert merges is not None
    assert any(m.replace("$", "").upper().startswith("B2") for m in merges)

    formulas = sheet.formulas()
    assert formulas is not None and formulas.num_rows >= 1
    fpd = formulas.to_pydict()
    # B2 → data row 0, col 1
    assert any(fpd["row"][i] == 0 and fpd["col"][i] == 1 for i in range(formulas.num_rows))

    comments = sheet.comments()
    assert comments is not None and comments.num_rows >= 1
    cpd = comments.to_pydict()
    assert any(r in cpd["ref"] for r in ("A2", "B2", "D2", "A4", "D4", "C4"))

    hlinks = sheet.hyperlinks()
    assert hlinks is not None and len(hlinks) >= 1
    refs_h = [h["ref"].split(":")[0] for h in hlinks]
    assert any(r in refs_h for r in ("A2", "B2", "D2", "C4"))

    wb = openpyxl.load_workbook(path, data_only=False)
    ws = wb.active

    for addr in ("A2", "D2", "A4", "D4", "C4"):
        cell = ws[addr]
        tr, tc = cell.row - 2, cell.column - 1
        tv = cell_value(rb, tr, tc)
        ov = cell.value
        # formula cells compared via formulas(); plain values here
        if not (isinstance(ov, str) and ov.startswith("=")):
            assert values_equal(tv, ov), f"{addr}: turbo={tv!r} oxl={ov!r}"
        xf = style_idx[tc][tr]
        rust = style_table[xf]
        assert rust["number_format"] == (cell.number_format or "General") or (
            cell.number_format not in (None, "General")
            and rust["number_format"] == cell.number_format
        ), f"{addr} fmt {rust['number_format']!r} vs {cell.number_format!r}"
        assert rust["font"]["bold"] is True
        assert rust["fill"]["pattern"] in ("solid", "none") or rust["fill"]["pattern"]

    # B2 formula text
    for i in range(formulas.num_rows):
        if fpd["row"][i] == 0 and fpd["col"][i] == 1:
            assert "1+2" in (fpd["text"][i] or "").replace(" ", "")
    wb.close()


# ---------------------------------------------------------------------------
# 4. Types
# ---------------------------------------------------------------------------


def test_stress_types():
    path = TESTDATA / "stress_types.xlsx"
    sheet = read_excel_turbo(str(path)).load_sheet(0, features="all")
    rb = sheet.to_arrow()

    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb.active
    wb_f = openpyxl.load_workbook(path, data_only=False)
    ws_f = wb_f.active

    # Native Arrow booleans (BooleanArray), not Float64 0/1 — assert explicitly.
    bool_col = 0
    assert rb.column(bool_col).type == "bool", (
        f"expected native Arrow bool, got {rb.column(bool_col).type}"
    )
    for orow in range(2, 6):
        ov = ws.cell(orow, 1).value
        if ov is None:
            continue
        tr = orow - 2
        tv = cell_value(rb, tr, 0)
        assert isinstance(ov, bool)
        assert tv is True if ov else tv is False, f"bool at row {orow}: expected {ov}, got {tv!r}"
        assert values_equal(tv, ov), f"bool map row {orow}: {tv} vs {ov}"

    # Unicode / entities / empty / long
    checks = [
        (2, 2, "emoji"),  # contains emoji marker
        (2, 3, "&"),  # entities
        (3, 3, "<"),
    ]
    for orow, ocol, needle in checks:
        tr, tc = orow - 2, ocol - 1
        tv = cell_value(rb, tr, tc)
        ov = ws.cell(orow, ocol).value
        assert values_equal(tv, ov), f"({orow},{ocol}) turbo={tv!r} oxl={ov!r}"
        if isinstance(tv, str):
            assert needle in tv or needle in (ov or "")

    # empty string: turbo may yield "" or None depending on storage
    tv_empty = cell_value(rb, 0, 3)  # D2
    ov_empty = ws.cell(2, 4).value
    assert ov_empty in ("", None) or ov_empty == ""
    assert tv_empty in ("", None), f"empty str: {tv_empty!r}"

    # long string 32k
    tv_long = cell_value(rb, 0, 4)
    ov_long = ws.cell(2, 5).value
    assert isinstance(tv_long, str) and len(tv_long) == len(ov_long) == 32000

    # floats
    for orow in (2, 3, 4, 5):
        ov = ws.cell(orow, 6).value
        if ov is None:
            continue
        tv = cell_value(rb, orow - 2, 5)
        assert values_equal(tv, ov, rel=1e-9), f"float row {orow}: {tv} vs {ov}"

    # date edge serials
    for orow in (2, 3, 4):
        ov = ws.cell(orow, 7).value
        tv = cell_value(rb, orow - 2, 6)
        if ov is None and tv is None:
            continue
        assert values_equal(tv, ov), f"date row {orow}: {tv} vs {ov}"

    # formula with entities / quoted comma
    formulas = sheet.formulas()
    assert formulas is not None and formulas.num_rows >= 1
    fpd = formulas.to_pydict()
    texts = fpd["text"]
    assert any("," in (t or "") or "&" in (t or "") for t in texts), texts

    wb.close()
    wb_f.close()


# ---------------------------------------------------------------------------
# 5. No sharedStrings / no styles.xml
# ---------------------------------------------------------------------------


def test_stress_noshared():
    path = TESTDATA / "stress_noshared.xlsx"
    sheet = read_excel_turbo(str(path)).load_sheet(0, features="all")
    rb = sheet.to_arrow()
    assert sheet.nrows >= 2
    assert cell_value(rb, 0, 0) == 11.0 or cell_value(rb, 0, 0) == 11
    assert cell_value(rb, 0, 1) == 22.0 or cell_value(rb, 0, 1) == 22
    assert cell_value(rb, 1, 0) == 33.0 or cell_value(rb, 1, 0) == 33
    assert cell_value(rb, 1, 1) == 44.0 or cell_value(rb, 1, 1) == 44
    # styles default xf 0
    si = sheet.style_indices()
    assert si is not None
    for c in range(sheet.ncols):
        for r in range(sheet.nrows):
            assert si[c][r] == 0


def test_stress_nostyles():
    path = TESTDATA / "stress_nostyles.xlsx"
    # Must not panic; values correct; styles default xf 0
    sheet = read_excel_turbo(str(path)).load_sheet(0, features="all")
    rb = sheet.to_arrow()
    assert sheet.column_names[0] == "h1"
    assert cell_value(rb, 0, 0) == 1.0
    assert cell_value(rb, 0, 1) == 2.0
    assert cell_value(rb, 1, 0) == 3.0
    # sparse C3=9 → col 2
    assert sheet.ncols >= 3
    assert cell_value(rb, 1, 2) == 9.0
    assert cell_value(rb, 1, 1) is None  # B3 empty
    si = sheet.style_indices()
    assert si is not None
    for c in range(sheet.ncols):
        for r in range(sheet.nrows):
            assert si[c][r] == 0
    st = sheet.style_table()
    assert st is not None  # empty/default style table, not crash


# ---------------------------------------------------------------------------
# Mixed-type columns preserve later values through safe string coercion
# ---------------------------------------------------------------------------


def test_mixed_type_column_preserves_later_numeric_as_string(tmp_path):
    """A string-first column must preserve a later numeric through coercion."""
    from openpyxl import Workbook

    path = tmp_path / "stress_mixedtype_probe.xlsx"
    wb = Workbook()
    ws = wb.active
    ws["A1"] = "h"
    ws["A2"] = "hello"  # string first → Str column
    ws["A3"] = 99.0  # number later is safely represented in the string column
    wb.save(path)
    wb.close()

    sheet = read_excel_turbo(str(path)).load_sheet(0, features="values")
    rb = sheet.to_arrow()
    assert cell_value(rb, 0, 0) == "hello"
    # openpyxl serializes the Python 99.0 as <v>99</v>; the scanner has no lexical
    # ".0" to recover, so the mixed column must yield "99" (not "99.0").
    assert cell_value(rb, 1, 0) == "99"


# ---------------------------------------------------------------------------
# Dense-path timing smoke (hard gate for release builds; debug is skipped)
# ---------------------------------------------------------------------------


def test_dense_timing_smoke():
    """Times mixed.xlsx values-only reads and enforces a release-only bound.

    An unoptimized debug ``_kyrax.pyd`` (byte-identical to ``target/debug/kyrax.dll``)
    would blow past the release threshold; such builds are explicitly identified and
    skipped so the gate cannot be silently waived for a slow release build.
    """
    import time

    if _is_debug_extension():
        pytest.skip(
            "loaded _kyrax is a debug build; the absolute timing gate is release-only"
        )

    p = str(TESTDATA / "mixed.xlsx")
    read_excel_turbo(p).load_sheet(0, features="values").to_arrow()  # warmup
    times = []
    for _ in range(5):
        t0 = time.perf_counter()
        read_excel_turbo(p).load_sheet(0, features="values").to_arrow()
        times.append(time.perf_counter() - t0)
    med = sorted(times)[len(times) // 2]
    # Hard bound for release builds: must stay well under a few seconds on this fixture
    assert med < 5.0, f"release dense path unexpectedly slow: median {med*1000:.1f} ms"
    print(f"\n[dense timing] mixed.xlsx values-only median={med*1000:.2f} ms samples={[round(t*1000,2) for t in times]}")
