from __future__ import annotations

from pathlib import Path

import pytest

import kyrax

from .utils import path_for_fixture

try:
    import pyarrow as pa  # noqa: F401

    PYARROW_AVAILABLE = True
except ImportError:  # pragma: no cover
    PYARROW_AVAILABLE = False

# Golden content: (data_row, data_col) -> error code. Positions are the 0-based
# data grid (header excluded); raw-grid positions add the header offset per case.
HEADER_ROWS = [
    ["a", "b", "c"],
    [1, "#DIV/0!", 3],
    [4, 5, "#N/A"],
    ["#VALUE!", 7, 8],
    [9, "#NAME?", 11],
]

NO_HEADER_ROWS = [
    [1, "#DIV/0!", 3],
    [4, 5, "#N/A"],
    ["#VALUE!", 7, 8],
    [9, "#NAME?", 11],
]

GOLDEN = {
    (0, 1): "#DIV/0!",
    (1, 2): "#N/A",
    (2, 0): "#VALUE!",
    (3, 1): "#NAME?",
}


def _write_xlsx(rows: list[list[object]]) -> bytes:
    return kyrax.write_excel_turbo_bytes([{"name": "Sheet1", "rows": rows}])


def _stock_cell_errors(
    source: str | bytes,
    header_row: int | None,
    dtype_cols: list[str | int],
):
    sheet = kyrax.read_excel(source).load_sheet(
        0, header_row=header_row, dtypes={col: "int" for col in dtype_cols}
    )
    _, cell_errors = sheet.to_arrow_with_errors()
    return cell_errors


def _stock_error_positions(source: str | bytes, header_row: int | None, dtype_cols: list[str | int]):
    errors = _stock_cell_errors(source, header_row, dtype_cols)
    return {
        "offset": {(e.offset_position[0], e.offset_position[1]) for e in errors.errors},
        "raw": {(e.position[0], e.position[1]) for e in errors.errors},
        "row_offsets": {e.row_offset for e in errors.errors},
    }


def _turbo_cell_errors(path: str, header_row: int | None):
    sheet = kyrax.read_excel_turbo(path).load_sheet("Sheet1", header_row=header_row)
    batch = sheet.cell_errors()
    return {
        (r, c): code
        for r, c, code in zip(
            batch.column("row").to_pylist(),
            batch.column("col").to_pylist(),
            batch.column("code").to_pylist(),
        )
    }


@pytest.mark.skipif(not PYARROW_AVAILABLE, reason="pyarrow not available")
def test_default_header_position_parity(tmp_path: Path) -> None:
    """Same workbook, both readers: identical CellErrors positions/content.

    Default single-header layout: position is the 0-based raw grid (data row + 1
    header row); offset_position is the 0-based data grid; row_offset == 1.
    """
    buf = _write_xlsx(HEADER_ROWS)
    path = tmp_path / "parity_errors.xlsx"
    path.write_bytes(buf)

    stock = _stock_error_positions(buf, header_row=0, dtype_cols=["a", "b", "c"])
    assert stock["offset"] == set(GOLDEN)
    assert stock["raw"] == {(r + 1, c) for r, c in GOLDEN}
    assert stock["row_offsets"] == {1}

    assert _turbo_cell_errors(str(path), header_row=0) == GOLDEN

    _, turbo_errors = kyrax.read_excel_turbo(str(path)).load_sheet("Sheet1").to_arrow_with_errors()
    turbo_raw = {(e.position[0], e.position[1]) for e in turbo_errors.errors}
    assert turbo_raw == stock["raw"]
    assert {e.row_offset for e in turbo_errors.errors} == {1}

    # Content: a string-dtype stock read sees the same error codes at the same cells.
    sheet = kyrax.read_excel(buf).load_sheet(
        0, header_row=0, dtypes={"a": "string", "b": "string", "c": "string"}
    )
    rb = sheet.to_arrow()
    for (dr, dc), code in GOLDEN.items():
        assert rb.column(dc).to_pylist()[dr] == code


@pytest.mark.skipif(not PYARROW_AVAILABLE, reason="pyarrow not available")
def test_headerless_position_parity(tmp_path: Path) -> None:
    """Headerless layout (header_row=None): position equals the 0-based data grid,
    row_offset == 0. Regresses the turbo hardcoded `row + 1` / `row_offset: 1`.
    """
    buf = _write_xlsx(NO_HEADER_ROWS)
    path = tmp_path / "parity_errors_noheader.xlsx"
    path.write_bytes(buf)

    stock = _stock_error_positions(buf, header_row=None, dtype_cols=[0, 1, 2])
    assert stock["offset"] == set(GOLDEN)
    assert stock["raw"] == set(GOLDEN)
    assert stock["row_offsets"] == {0}

    assert _turbo_cell_errors(str(path), header_row=None) == GOLDEN

    _, turbo_errors = (
        kyrax.read_excel_turbo(str(path)).load_sheet("Sheet1", header_row=None).to_arrow_with_errors()
    )
    turbo_raw = {(e.position[0], e.position[1]) for e in turbo_errors.errors}
    assert turbo_raw == set(GOLDEN)
    assert {e.row_offset for e in turbo_errors.errors} == {0}


@pytest.mark.skipif(not PYARROW_AVAILABLE, reason="pyarrow not available")
def test_xls_twin_position_parity() -> None:
    """The same workbook saved as legacy .xls produces identical CellErrors.

    Fixture is generated by Excel COM (see scripts/generate_parity_errors_xls.ps1)
    when Excel is available; skipped when the fixture has not been checked in.
    """
    fixture = Path(path_for_fixture("parity_errors.xls"))
    if not fixture.is_file():
        pytest.skip("parity_errors.xls fixture absent (generate via Excel COM)")

    stock = _stock_error_positions(str(fixture), header_row=0, dtype_cols=["a", "b", "c"])
    assert stock["offset"] == set(GOLDEN)
    assert stock["raw"] == {(r + 1, c) for r, c in GOLDEN}
    assert stock["row_offsets"] == {1}