name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"
      - name: Set up rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Build & Check Docs
        run: |
          make install
          make doc
      - name: Deploy Docs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          uv run mkdocs gh-deploy --force
